### ISSUE TITLE
outline effect pushes game object away from the center of the camera when using setVelocity();

### ISSUE THREAD

**Issue by AndysonDK** [rexrainbow/phaser3-rex-notes#116]
As you can see on the image below:
![image](https://user-images.githubusercontent.com/28491857/89404829-e63b7800-d71a-11ea-9346-ab84939db50f.png)

The whole game object is being pushed a little bit away from the center which you can see as the game object is a little bit out of the purple circle. Note that I've made a call to `setVelocityX(-500);` in the image above.
The purple circle and the green line showing direction and velocity is generated by enabling arcade debug mode.

If I remove the outline effect:
```JavaScript
//effectLayer.add(image);
```
The game object is centered within the purple circle when using `setVelocity();` as expected:
<img width="630" alt="Anmærkning 2020-08-05 130114" src="https://user-images.githubusercontent.com/28491857/89405396-c5275700-d71b-11ea-8e27-93f8d036759d.png">

I would like to have the outline effect applied but without that little push outside of the center of the camera when moving the game object using `setVelocity();`

The code that I'm using is excatly the same as in the last issue that I posted:
https://github.com/rexrainbow/phaser3-rex-notes/issues/114

Again this might be a problem with my own code or just how phaser moves game objects using `setVelocity();`

**Comment by rexrainbow** [comment]
Sorry I can't reproduce this issue. [My test](https://codepen.io/rexrainbow/pen/oNxNdww): apply outline effect on arcade physics game object seems working fine.

**Comment by rexrainbow** [comment]
Okey, I [reproduce](https://codepen.io/rexrainbow/pen/oNxNdww) this issue now, outline effect in camera follows a moving game object is not correct. This issue might be more complex. I can try to fix it later.

I has another [outline effect shader](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shader-outline/) which apply on camera directly, it might not have this issue. But it can't add/remove outline target  during runtime easily.

**Comment by rexrainbow** [comment]
Sorry I can't solve this issue. 
Because that camera is scrolled between 'postupdate'/'prerender' and rendering. Outline effect game object can't get correct target position related on screen.

1.  'postupdate'  event
    - OutlineEffect draw target game object to internal rendertexture
2. Camera follows game object, set it's scrollX, scrollY
3. Render

Here is a workaround , see this [demo](https://codepen.io/rexrainbow/pen/oNxNdww), with my updated OutlineEffect game object.
1. Add 'prerender' event to set camera's scrollX, scrollY to follow game object, line 16 - 20
2. Create OutlineEffect game object ( I moved the drawing process to 'prerender' event) **after step1**. line 22.

**Comment by AndysonDK** [comment]
Nice your workaround works, thanks for your time!
