### ISSUE TITLE
Setting up with the monopoly example

### ISSUE THREAD

**Issue by lorenzoc25** [rexrainbow/phaser3-rex-notes#183]
Hi!
I checked your notes on the monopoly part and found the plug-in very promising. However, I'm having trouble replicate and set up the plugin on my end... the [docs](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-monopoly/) here are pretty confusing(like there are a lot of replicated code and the purposes are not well explained). So is there any chance that you might update the doc and make it clearer? That would be super heplful

**Comment by rexrainbow** [comment]
The document of setting [board](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#add-board-object), and setting [moveTo](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-moveto/#create-instance)
Which part of document is not clearly?

**Comment by lorenzoc25** [comment]
I'm having trouble loading the plug in and setting up the board from the start. The variable "board" is defined multiple times, and the purpose of the class "MyBoard" was not made clear. How exactly should we use those?

**Comment by rexrainbow** [comment]
In the [Install plugin](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-monopoly/#install-plugin), user has 3 possible ways to use it.

- [Load minify file from url](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-monopoly/#load-minify-file) : Plugin is an exteranl file. This solution is suitable for loading plugins in [codepen demo](https://codepen.io/rexrainbow/pen/WWJxZL).
- [Use `import` to include plugin](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-monopoly/#import-plugin) : Plugin can pack with source code together. I use this solution in my local testing.
- [Import class to  extend it](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-monopoly/#import-plugin) : Using custom class instead of plugin.

You can try *Load minify file from url* solution first, 2nd and 3rd solution need to deal with `npm`, and `pacakage.json`.
