### ISSUE TITLE
addBackground covers added elements to sizer

### ISSUE THREAD

**Issue by djdabs** [rexrainbow/phaser3-rex-notes#276]
The commented out line is the one that makes this change. Would like the background to be behind the added elements. Is that possible?

```
 const elemSizer = scene.rexUI.add.sizer({
            width: GRID_COLS_WIDTH,
            height: GRID_COLS_HEIGHT,
            orientation: 'x',
            name: 'item_' + key,
        })
        // .addBackground(scene.rexUI.add.roundRectangle(0, 0, 0, 0, 20, UX_PRIMARY))
        .add(iconSizer)
        .add(textCenterized)
        .layout()
```
![CleanShot 2022-04-20 at 14 47 04](https://user-images.githubusercontent.com/87738563/164328765-5032b32f-13ae-4cd1-8612-1932ae7e2707.png)
![CleanShot 2022-04-20 at 14 47 23](https://user-images.githubusercontent.com/87738563/164328775-24ba8ac5-0dd6-441d-a9d1-86c15690e7c6.png)

**Comment by rexrainbow** [comment]
Children game objects of containerLite/sizers are placed in display list of scene, containerLite/sizers won't change render order of children game objects.

There are some possible solutions : 
- Create background game object earlier, before all added elements. So that background game object will add to display list of scene before added elements. It is the simplest way. or
- Set [depth](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/gameobject/#depth-z-index) of background game object, or depth of added elements. or
- Put background game object, and added elements into 2 [layers](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/layer/).

**Comment by djdabs** [comment]
Thanks for the reply! Will try these out
