### ISSUE TITLE
ScrollablePanel - setDepth on children prevents scrolling

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#490]
I am adding Phaser.GameObject.Containers to scrollable panel. I have a click event on each individual container.

If I don't set depth on the panel children, I can't click them, but I can scroll.

If I set a depth that's above the panel's depth, I can click them, but then I can't scroll.

You'll notice this is also the case with your [demo](https://codepen.io/rexrainbow/pen/eYOdKBR).

I need to scroll, but also click on child elements. Any thoughts?

**Comment by rexrainbow** [comment]
The root cause is [`scene.input.topOnly`](https://docs.phaser.io/phaser/concepts/input) is set to `true`. So, the simplest solution is to set `scene.input.topOnly` to `fasle`.
If this solution is not acceptable, you might move your input events on [`setChildrenInteractive`](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#set-children-interactive) related events. See this [demo](https://codepen.io/rexrainbow/pen/YMyBom), line 120, 133.

[Reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#input-events)

**Comment by dtturcotte** [comment]
Setting `scene.input.topOnly = false` solved the issue, thanks!! Any side effects I should know of for setting it to false?

**Comment by rexrainbow** [comment]
For example, there has multiple (modal) dialogs on a scene, user might click overlapped buttons on different dialogs.

**Comment by dtturcotte** [comment]
Second question: is there any reason why adding scrollable panel, with child `phaser.gameobject.containers`, to a parent `phaser.gameobject.container` would break scrolling and display of elements (it works when the scrollable panel is added directly to the scene)?

**Comment by rexrainbow** [comment]
Position of mask inside a built-in container is not working well. [issue](https://github.com/phaserjs/phaser/issues/6177)
