### ISSUE TITLE
critical bug for Sizer

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#77]
https://codepen.io/jcyuan/pen/OJVRKVo
this is the live demo besed on the official [`Nested sizer`](https://codepen.io/rexrainbow/pen/NOzorp), if add bitmapFont to a `sizer`, everything of the sizer will disappear, without bitmap font child, everything work fine (comment out line 97). this does not exist in the older version of rexUI plugin (should be 2019-12 sorry there is no release number), and the version has this issue is the version I updated the day before yesterday.

**Comment by rexrainbow** [comment]
Any sizer game object will use properties `displayWidth` and `displayHeight` to calculate the position of children game object. Using `displayWidth` and `displayHeight` is better then `width` and `height`, since game object might be scaled.

BitmapText game object has [`width`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/bitmaptext/static/BitmapText.js#L602) and [`height`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/bitmaptext/static/BitmapText.js#L621) indeed, but it dose not have `displayWidth` and `displayHeight` properties. thus sizer won't layout children correctly. 

I will try to add more logic to use `width`, `height` property if there is no `displayWidth` and `displayHeight` properties available for workaround. 
The better solution is adding  `displayWidth` and `displayHeight` properties into BitmapText game object, because that BitmapText game object has `width` and `height` properties and it is renderable, it ought to have `displayWidth` and `displayHeight` properties.

**Comment by jcyuan** [comment]
oh! it does make sense, so I think this should be fixed from Phaser official. I'll temporarily patch for now for our project.

**Comment by rexrainbow** [comment]
Changing updated, now (official) BitmapText game object can be used in sizer correctly.

**Comment by jcyuan** [comment]
so efficiency!! thanks so much again @rexrainbow  ;D
