### ISSUE TITLE
add new action dynamically for dialog

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#86]
const actions = this._dialog.getElement('actionsSizer') as RexPlugins.UI.Buttons;
    actions.add(...);
    actions.layout();

this snippet works, but the newly added button has a wrong depth... it's placed behind the background.

is this way to add new action right or wrong?
thanks.

**Comment by rexrainbow** [comment]
RexUI won't change depth of children game obejects, you can set depth via `gameObject.setDepth()`, or create background object before icon, text game objects. Elder game object will be placed behind newer game object.

**Comment by jcyuan** [comment]
@rexrainbow yes, sorry that was my mistake: I created the new button with the wrong scene different from the dialog's.

**Comment by rexrainbow** [comment]
Label can't cover all possible use-cases. Try build your own ui component extended from [sizer](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-sizer/) class, Label is extended from sizer too.

**Comment by jcyuan** [comment]
no I think you misunderstood. I don't use `Label`

the dialog's actions area is actually a `Buttons` class.

https://github.com/rexrainbow/phaser3-rex-notes/blob/c7d448896b58f4b4329f5a658a96ed675529d15b/templates/ui/buttons/Buttons.js#L69-L70

the button gameobjects managed by the `Buttons` class, are only set click event in the `Buttons` constructor, later when you call `add`, you are actually calling `sizer.add`, I think `Buttons` class should override the base `add` method?

**Comment by rexrainbow** [comment]
Good feature suggestion, I will try to implement it later.

**Comment by jcyuan** [comment]
thanks so much!

**Comment by rexrainbow** [comment]
Another workaround solution is creating enough buttons during constructing, then show/hide buttons.
[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-dialog/show-hide-button.js) is an example,
1. [Create dialog](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-dialog/show-hide-button.js#L47-L103) with 5 choice buttons, and 3 action buttons.
2. [Set properties of dialog](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-dialog/show-hide-button.js#L121-L153): 
    - [show/hide choice buttons](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-dialog/show-hide-button.js#L130-L138), 
    - [show/hide action buttons](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-dialog/show-hide-button.js#L143-L151)

This solution could reuse game objects without creating/destroying anything.

I will still add `adding new button` feature. Since there has an `adding button` , it is better to have `remove button` and `clear buttons` methods.

**Comment by jcyuan** [comment]
you are the best!!
will update now and have a try. thanks so much!
